//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACRHelix.Feature.ACRDashboard.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuickLink
    {
        public int LinkId { get; set; }
        public string PersonifyID { get; set; }
        public string LinkName { get; set; }
        public string LinkUrl { get; set; }
    }
}
