//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACR.Library.DataContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ACR_APP_DATA_Entities : DbContext
    {
        public ACR_APP_DATA_Entities()
            : base("name=ACR_APP_DATA_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Designation_Dropdown> Designation_Dropdown { get; set; }
        public virtual DbSet<Locality_Dropdown> Locality_Dropdown { get; set; }
        public virtual DbSet<Modality_Dropdown> Modality_Dropdown { get; set; }
    }
}
