//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACR.Library.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Designation_Dropdown
    {
        public string DesignationList_value { get; set; }
        public string DesignationList_text { get; set; }
        public int DesignationList_ListOrder { get; set; }
        public int DesignationList_bitvalue { get; set; }
    }
}
