//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACR.Library.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modality_Dropdown
    {
        public string ModalityList_value { get; set; }
        public string ModalityList_text { get; set; }
        public string Short_description { get; set; }
    }
}
