//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Last Generation - 11/7/2014 4:37:53 PM
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     If you need to regenerate this code, run /velir/GenerateItemReferences.aspx
// </auto-generated>
//------------------------------------------------------------------------------

using System.Configuration;
using System.Collections.Specialized;
using ACR.Library.Reference.Wrappers;

namespace ACR.Library.Reference
{
	public class ItemReference
	{
		public static ItemReferenceObject Home { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["Home"]);}}
		public static ItemReferenceObject ErrorPage { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["ErrorPage"]);}}
		public static ItemReferenceObject Airp { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["Airp"]);}}
		public static ItemReferenceObject Airp_GlobalSettings { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["Airp.GlobalSettings"]);}}
		public static ItemReferenceObject Airp_GlobalSettings_TopNavigation { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["Airp.GlobalSettings.TopNavigation"]);}}
		public static ItemReferenceObject Airp_GlobalSettings_LeftNavigation { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["Airp.GlobalSettings.LeftNavigation"]);}}
		public static ItemReferenceObject Airp_GlobalSettings_FooterNavigation { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["Airp.GlobalSettings.FooterNavigation"]);}}
		public static ItemReferenceObject Radpac { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["Radpac"]);}}
		public static ItemReferenceObject Radpac_ImagingProfessionals { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["Radpac.ImagingProfessionals"]);}}
		public static ItemReferenceObject Radpac_AboutUs_ParticipatingOrganizations { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["Radpac.AboutUs.ParticipatingOrganizations"]);}}
		public static ItemReferenceObject Radpac_AboutUs_KeyContributors { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["Radpac.AboutUs.KeyContributors"]);}}
		public static ItemReferenceObject Radpac_Global_HomePageAds { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["Radpac.Global.HomePageAds"]);}}
		public static ItemReferenceObject Radpac_Global_SiteConfigurationSettings { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["Radpac.Global.SiteConfigurationSettings"]);}}
		public static ItemReferenceObject Radpac_Global_SocialMediaLinks { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["Radpac.Global.SocialMediaLinks"]);}}
		public static ItemReferenceObject Radpac_Login { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["Radpac.Login"]);}}
		public static ItemReferenceObject RLI { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["RLI"]);}}
		public static ItemReferenceObject RLI_Search { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["RLI.Search"]);}}
		public static ItemReferenceObject RLI_Settings { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["RLI.Settings"]);}}
		public static ItemReferenceObject RLI_EventTypes { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["RLI.EventTypes"]);}}
		public static ItemReferenceObject RLI_EventTags { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["RLI.EventTags"]);}}
        public static ItemReferenceObject RLI_Header_BannerAd { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["RLI.Widgets.Header.BannerAd"]); } }
		public static ItemReferenceObject ImageWisely { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["ImageWisely"]);}}
		public static ItemReferenceObject IW_HomepageRotatingCarouselFolder { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["IW.HomepageRotatingCarouselFolder"]);}}
		public static ItemReferenceObject IW_ImagingProfessionals_Landing { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["IW.ImagingProfessionals.Landing"]);}}
		public static ItemReferenceObject IW_ImagingProfessionals_ImagingPhysicians { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["IW.ImagingProfessionals.ImagingPhysicians"]);}}
		public static ItemReferenceObject IW_ImagingProfessionals_ImagingTechnologists { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["IW.ImagingProfessionals.ImagingTechnologists"]);}}
		public static ItemReferenceObject IW_ImagingProfessionals_MedicalPhysicists { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["IW.ImagingProfessionals.MedicalPhysicists"]);}}
		public static ItemReferenceObject IW_ImagingProfessionals_NuclearMedicine { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["IW.ImagingProfessionals.NuclearMedicine"]);}}
		public static ItemReferenceObject IW_LogoFolder { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["IW.LogoFolder"]);}}
		public static ItemReferenceObject IW_ReferringPracticioners { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["IW.ReferringPracticioners"]);}}
		public static ItemReferenceObject IW_Patients { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["IW.Patients"]);}}
		public static ItemReferenceObject IW_EquipmentResources_Landing { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["IW.EquipmentResources.Landing"]);}}
		public static ItemReferenceObject IW_EquipmentResources_Vendors { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["IW.EquipmentResources.Vendors"]);}}
		public static ItemReferenceObject IW_AboutUs_Landing { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["IW.AboutUs.Landing"]);}}
		public static ItemReferenceObject IW_AboutUs_ParticipatingOrganizations { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["IW.AboutUs.ParticipatingOrganizations"]);}}
		public static ItemReferenceObject IW_AboutUs_ExecutiveCommitteeMembers { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["IW.AboutUs.ExecutiveCommitteeMembers"]);}}
		public static ItemReferenceObject IW_AboutUs_KeyContributors { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["IW.AboutUs.KeyContributors"]);}}
		public static ItemReferenceObject IW_AboutUs_TaskForce { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["IW.AboutUs.TaskForce"]);}}
		public static ItemReferenceObject IW_Pledge_Landing { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["IW.Pledge.Landing"]);}}
		public static ItemReferenceObject IW_Pledge_HonorRoll { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["IW.Pledge.HonorRoll"]);}}
		public static ItemReferenceObject IW_Pledge_ImagingProfsForm { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["IW.Pledge.ImagingProfsForm"]);}}
		public static ItemReferenceObject IW_Pledge_ImagingProfsPledgesMade { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["IW.Pledge.ImagingProfsPledgesMade"]);}}
		public static ItemReferenceObject IW_Pledge_ReferringProviderForm { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["IW.Pledge.ReferringProviderForm"]);}}
		public static ItemReferenceObject IW_Pledge_ReferringProviderPledgesMade { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["IW.Pledge.ReferringProviderPledgesMade"]);}}
		public static ItemReferenceObject IW_Pledge_AssociationForm { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["IW.Pledge.AssociationForm"]);}}
		public static ItemReferenceObject IW_Pledge_AssociationPledgesMade { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["IW.Pledge.AssociationPledgesMade"]);}}
		public static ItemReferenceObject IW_Pledge_FacilityForm { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["IW.Pledge.FacilityForm"]);}}
		public static ItemReferenceObject IW_Pledge_FacilityPledgesMade { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["IW.Pledge.FacilityPledgesMade"]);}}
		public static ItemReferenceObject IW_Pledge_ThankYou { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["IW.Pledge.ThankYou"]);}}
		public static ItemReferenceObject IW_Pledge_RolesFolder { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["IW.Pledge.RolesFolder"]);}}
		public static ItemReferenceObject IW_ContactUs { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["IW.ContactUs"]);}}
		public static ItemReferenceObject IW_MediaRoom { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["IW.MediaRoom"]);}}
		public static ItemReferenceObject IW_Global_SiteConfigurationSettings { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["IW.Global.SiteConfigurationSettings"]);}}
		public static ItemReferenceObject IW_Global_PatientImagingHistoryCard { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["IW.Global.PatientImagingHistoryCard"]);}}
		public static ItemReferenceObject IW_Global_HomePageAds { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["IW.Global.HomePageAds"]);}}
		public static ItemReferenceObject IW_Global_SocialMediaLinks { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["IW.Global.SocialMediaLinks"]);}}
		public static ItemReferenceObject IW_Global_PledgeFormType_Association { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["IW.Global.PledgeFormType.Association"]);}}
		public static ItemReferenceObject IW_Global_PledgeFormType_Facility { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["IW.Global.PledgeFormType.Facility"]);}}
		public static ItemReferenceObject IW_Global_PledgeFormType_ImagingProfessional { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["IW.Global.PledgeFormType.ImagingProfessional"]);}}
		public static ItemReferenceObject IW_Global_PledgeFormType_ReferringProvider { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["IW.Global.PledgeFormType.ReferringProvider"]);}}
		public static ItemReferenceObject ACR_Home { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["ACR.Home"]);}}
		public static ItemReferenceObject ACR_Global_Footer { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["ACR.Global.Footer"]);}}
		public static ItemReferenceObject ACR_Global_Header { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["ACR.Global.Header"]);}}
		public static ItemReferenceObject ACR_Global_Enumerations_StaffMemberTypes { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["ACR.Global.Enumerations.StaffMemberTypes"]);}}
		public static ItemReferenceObject ACR_Global_Enumerations_CPICategories { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["ACR.Global.Enumerations.CPICategories"]);}}
		public static ItemReferenceObject ACR_Global_Enumerations_CPISpliceCategories { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["ACR.Global.Enumerations.CPISpliceCategories"]);}}
		public static ItemReferenceObject ACR_Global_ParentRedirectPage { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["ACR.Global.ParentRedirectPage"]);}}
		public static ItemReferenceObject ACR_FeaturedContentCarosel { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["ACR.FeaturedContentCarosel"]);}}
		public static ItemReferenceObject ACR_FeaturedContentManualCarousel { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["ACR.FeaturedContentManualCarousel"]);}}
		public static ItemReferenceObject ACR_FeaturedContentLinkFolder { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["ACR.FeaturedContentLinkFolder"]);}}
		public static ItemReferenceObject ACR_AboutUs { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["ACR.AboutUs"]);}}
        public static ItemReferenceObject ACR_AboutUs_ACRFoundation { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["ACR.AboutUs.ACRFoundation"]); } }
		public static ItemReferenceObject ACR_AboutUs_ContactUs_ReportABug { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["ACR.AboutUs.ContactUs.ReportABug"]);}}
		public static ItemReferenceObject ACR_QualitySafety { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["ACR.QualitySafety"]);}}
		public static ItemReferenceObject ACR_FacilitySearch { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["ACR.FacilitySearch"]);}}
		public static ItemReferenceObject ACR_Education { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["ACR.Education"]);}}
		public static ItemReferenceObject ACR_Education_FacultyList { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["ACR.Education.FacultyList"]);}}
		public static ItemReferenceObject ACR_Education_CpiExpertsList { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["ACR.Education.CpiExpertsList"]);}}
		public static ItemReferenceObject ACR_Education_CpiSpliceExpertsList { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["ACR.Education.CpiSpliceExpertsList"]);}}
		public static ItemReferenceObject ACR_Advocacy { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["ACR.Advocacy"]);}}
		public static ItemReferenceObject ACR_Membership { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["ACR.Membership"]);}}
		public static ItemReferenceObject ACR_ClinicalResearch { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["ACR.ClinicalResearch"]);}}
		public static ItemReferenceObject ACR_MeetingsEvents { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["ACR.MeetingsEvents"]);}}
		public static ItemReferenceObject ACR_NewsPublications { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["ACR.NewsPublications"]);}}
		public static ItemReferenceObject ACR_NewsPublications_News { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["ACR.NewsPublications.News"]);}}
		public static ItemReferenceObject ACR_NewsPublications_NewsArticleTypeLocation { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["ACR.NewsPublications.NewsArticleTypeLocation"]);}}
		public static ItemReferenceObject ACR_NewsPublications_NewsArticleType_Advocacy { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["ACR.NewsPublications.NewsArticleType.Advocacy"]);}}
		public static ItemReferenceObject ACR_NewsPublications_NewsArticleType_QualityCare { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["ACR.NewsPublications.NewsArticleType.QualityCare"]);}}
		public static ItemReferenceObject ACR_NewsPublications_News_QualityCare { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["ACR.NewsPublications.News.QualityCare"]);}}
		public static ItemReferenceObject ACR_Login { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["ACR.Login"]);}}
		public static ItemReferenceObject ACR_Login_Help { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["ACR.Login.Help"]);}}
		public static ItemReferenceObject ACR_MeetingsAndEventsCalendar { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["ACR.MeetingsAndEventsCalendar"]);}}
		public static ItemReferenceObject ACR_EducationCalendar { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["ACR.EducationCalendar"]);}}
		public static ItemReferenceObject ACR_EducationCatalogLanding { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["ACR.EducationCatalogLanding"]);}}
		public static ItemReferenceObject ACR_EducationCatalogSearch { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["ACR.EducationCatalogSearch"]);}}
		public static ItemReferenceObject ACR_EducationCenter_Products { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["ACR.EducationCenter.Products"]);}}
		public static ItemReferenceObject ACR_ProductStubs { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["ACR.ProductStubs"]);}}
		public static ItemReferenceObject ACR_ProductArea_MTG { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["ACR.ProductArea.MTG"]);}}
		public static ItemReferenceObject ACR_ProductClass_MTG_AIRP { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["ACR.ProductClass.MTG.AIRP"]);}}
		public static ItemReferenceObject ACR_ProductClass_MTG_RLI { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["ACR.ProductClass.MTG.RLI"]);}}
		public static ItemReferenceObject ACR_Membership_Chapters { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["ACR.Membership.Chapters"]);}}
		public static ItemReferenceObject ACR_MeetingType_ACR { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["ACR.MeetingType.ACR"]);}}
		public static ItemReferenceObject ACR_MeetingType_AIRP { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["ACR.MeetingType.AIRP"]);}}
		public static ItemReferenceObject ACR_MeetingType_EducationCenter { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["ACR.MeetingType.EducationCenter"]);}}
		public static ItemReferenceObject ACR_MeetingType_RLI { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["ACR.MeetingType.RLI"]);}}
		public static ItemReferenceObject ACR_Error_404 { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["ACR.Error.404"]);}}
		public static ItemReferenceObject ACR_Error_401 { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["ACR.Error.401"]);}}
		public static ItemReferenceObject ACR_Error_500 { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["ACR.Error.500"]);}}
		public static ItemReferenceObject ACR_Search_General { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["ACR.Search.General"]);}}
		public static ItemReferenceObject ACR_FAQListing { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["ACR.FAQListing"]);}}
		public static ItemReferenceObject ACR_Media_PDFIcon { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["ACR.Media.PDFIcon"]);}}
		public static ItemReferenceObject ACR_Media_MediaRoot { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["ACR.Media.MediaRoot"]);}}
		public static ItemReferenceObject ACR_Taxonomy { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["ACR.Taxonomy"]);}}
		public static ItemReferenceObject ACR_Taxonomy_ABRCodesRoot { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["ACR.Taxonomy.ABRCodesRoot"]);}}
		public static ItemReferenceObject ACR_Taxonomy_DeliveryMethodsRoot { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["ACR.Taxonomy.DeliveryMethodsRoot"]);}}
		public static ItemReferenceObject ACR_Taxonomy_InterestsRoot { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["ACR.Taxonomy.InterestsRoot"]);}}
		public static ItemReferenceObject ACR_Taxonomy_ModalitiesRoot { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["ACR.Taxonomy.ModalitiesRoot"]);}}
		public static ItemReferenceObject ACR_Taxonomy_ProductAreasRoot { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["ACR.Taxonomy.ProductAreasRoot"]);}}
		public static ItemReferenceObject ACR_Taxonomy_ProductClassRoot { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["ACR.Taxonomy.ProductClassRoot"]);}}
		public static ItemReferenceObject ACR_Taxonomy_ProductTypesRoot { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["ACR.Taxonomy.ProductTypesRoot"]);}}
		public static ItemReferenceObject ACR_Taxonomy_ProductTypes_Meeting { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["ACR.Taxonomy.ProductTypes.Meeting"]);}}
		public static ItemReferenceObject ACR_Taxonomy_SubspecialtiesRoot { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["ACR.Taxonomy.SubspecialtiesRoot"]);}}
		public static ItemReferenceObject ACR_Taxonomy_TopicsRoot { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["ACR.Taxonomy.TopicsRoot"]);}}
		public static ItemReferenceObject ACR_Taxonomy_RolesRoot { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["ACR.Taxonomy.RolesRoot"]);}}
		public static ItemReferenceObject ACR_Taxonomy_CreditTypesRoot { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["ACR.Taxonomy.CreditTypesRoot"]);}}
		public static ItemReferenceObject MSL_AnnualRemindersFolder { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["MSL.AnnualRemindersFolder"]);}}
		public static ItemReferenceObject MSL_FacilitySearch { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["MSL.FacilitySearch"]);}}
		public static ItemReferenceObject ACR_Settings_BrightcoveSettings { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["ACR.Settings.BrightcoveSettings"]);}}
		public static ItemReferenceObject ACR_Settings_AddThisSettings { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["ACR.Settings.AddThisSettings"]);}}
		public static ItemReferenceObject ACR_Settings_CoveoMediaAssociations { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["ACR.Settings.CoveoMediaAssociations"]); } }
		public static ItemReferenceObject Devices_Default { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["Devices.Default"]);}}
		public static ItemReferenceObject Devices_Print { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["Devices.Print"]);}}
		public static ItemReferenceObject Templates_AcrCommon { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["Templates.AcrCommon"]);}}
		public static ItemReferenceObject Templates_Widget_Location { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["Templates.Widget.Location"]);}}
		public static ItemReferenceObject ACR_Header_BannerAd { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["ACR.Widgets.Header.BannerAd"]); } }
		public static ItemReferenceObject ACR_RightRail_Sales { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["ACR.Widgets.RightRail.BannerAd"]); } }
		public static ItemReferenceObject ACR_RightRail_Sales_Advertisements { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["ACR.Widgets.RightRail.Sales.Advertisements"]); } }

        //The become a member page is moving from Sitecore to Personify, so this no longer references an item, but a string.
        //public static ItemReferenceObject ACR_Membership_BecomeAMember { get { return new ItemReferenceObject(((NameValueCollection)ConfigurationManager.GetSection("SiteReference/ItemReference"))["ACR.Membership.BecomeAMember"]); } }
        public static string ACR_Membership_BecomeAMember = "https://shop.acr.org/ACRMembership/ACRGetStarted.aspx";
	}
}
