//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ACRMicroSites.com.imagewisely.PledgesService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PledgesServiceSoap", Namespace="http://www.imagewisely.org/")]
    public partial class PledgesService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback IncrementPledgeCounterOperationCompleted;
        
        private System.Threading.SendOrPostCallback ResetPledgeCounterOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PledgesService() {
            this.Url = global::ACRMicroSites.Properties.Settings.Default.ACRMicroSites_com_imagewisely_PledgesService_PledgesService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event IncrementPledgeCounterCompletedEventHandler IncrementPledgeCounterCompleted;
        
        /// <remarks/>
        public event ResetPledgeCounterCompletedEventHandler ResetPledgeCounterCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.imagewisely.org/IncrementPledgeCounter", RequestNamespace="http://www.imagewisely.org/", ResponseNamespace="http://www.imagewisely.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool IncrementPledgeCounter(string skey) {
            object[] results = this.Invoke("IncrementPledgeCounter", new object[] {
                        skey});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IncrementPledgeCounterAsync(string skey) {
            this.IncrementPledgeCounterAsync(skey, null);
        }
        
        /// <remarks/>
        public void IncrementPledgeCounterAsync(string skey, object userState) {
            if ((this.IncrementPledgeCounterOperationCompleted == null)) {
                this.IncrementPledgeCounterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIncrementPledgeCounterOperationCompleted);
            }
            this.InvokeAsync("IncrementPledgeCounter", new object[] {
                        skey}, this.IncrementPledgeCounterOperationCompleted, userState);
        }
        
        private void OnIncrementPledgeCounterOperationCompleted(object arg) {
            if ((this.IncrementPledgeCounterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IncrementPledgeCounterCompleted(this, new IncrementPledgeCounterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.imagewisely.org/ResetPledgeCounter", RequestNamespace="http://www.imagewisely.org/", ResponseNamespace="http://www.imagewisely.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ResetPledgeCounter(string skey, int countFromDb) {
            object[] results = this.Invoke("ResetPledgeCounter", new object[] {
                        skey,
                        countFromDb});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ResetPledgeCounterAsync(string skey, int countFromDb) {
            this.ResetPledgeCounterAsync(skey, countFromDb, null);
        }
        
        /// <remarks/>
        public void ResetPledgeCounterAsync(string skey, int countFromDb, object userState) {
            if ((this.ResetPledgeCounterOperationCompleted == null)) {
                this.ResetPledgeCounterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnResetPledgeCounterOperationCompleted);
            }
            this.InvokeAsync("ResetPledgeCounter", new object[] {
                        skey,
                        countFromDb}, this.ResetPledgeCounterOperationCompleted, userState);
        }
        
        private void OnResetPledgeCounterOperationCompleted(object arg) {
            if ((this.ResetPledgeCounterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ResetPledgeCounterCompleted(this, new ResetPledgeCounterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void IncrementPledgeCounterCompletedEventHandler(object sender, IncrementPledgeCounterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IncrementPledgeCounterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IncrementPledgeCounterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ResetPledgeCounterCompletedEventHandler(object sender, ResetPledgeCounterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ResetPledgeCounterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ResetPledgeCounterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591