//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACR.Foundation.ExpressUrls.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ExpressUrlDatabase : DbContext
    {
        public ExpressUrlDatabase()
            : base("name=ExpressUrlDatabase")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UrlMap> UrlMaps { get; set; }
        public virtual DbSet<PageNotFoundRedirect> PageNotFoundRedirects { get; set; }
    }
}
