//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACR.Foundation.ExpressUrls.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageNotFoundRedirect
    {
        public string NotFoundUrl { get; set; }
        public string NewUrl { get; set; }
        public System.DateTime DateModified { get; set; }
    }
}
