//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACR.Foundation.ExpressUrls.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrlMap
    {
        public int urlMapId { get; set; }
        public string sourceUrl { get; set; }
        public string destSitecoreId { get; set; }
        public string destUrl { get; set; }
        public bool isUserDefined { get; set; }
        public string siteName { get; set; }
        public string queryString { get; set; }
    }
}
