//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACR.Library.Ideas.Data
{
    using System;
    
    public partial class FacilitiesAndPhysicianByZipCodeDB
    {
        public string NAME { get; set; }
        public string STREET { get; set; }
        public string STREET2 { get; set; }
        public string CITY { get; set; }
        public string STATE_ID { get; set; }
        public string ZIP { get; set; }
        public string PHONE { get; set; }
        public string LATITUDE { get; set; }
        public string LONGITUDE { get; set; }
        public string Miles { get; set; }
    }
}
