//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACR.Library.Ideas.Data
{
    using System;
    
    public partial class FacilitiesAndPhysicianDB
    {
        public string NAME { get; set; }
        public string Sta_ID { get; set; }
        public string Sta_name { get; set; }
        public string PHONE { get; set; }
        public int Physician { get; set; }
        public int Facilities { get; set; }
        public string FullAddress { get; set; }
    }
}
