//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACR.Library.Ideas.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class IdeasDataEntities : DbContext
    {
        public IdeasDataEntities()
            : base("name=IdeasDataEntities")
        {
        }

        public IdeasDataEntities(string nameOrConnectionString) : base(nameOrConnectionString)
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PRACTICE> PRACTICEs { get; set; }
    
        public virtual ObjectResult<FacilitiesAndPhysicianDB> GetFacilitiesAndPhysician()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FacilitiesAndPhysicianDB>("GetFacilitiesAndPhysician");
        }
    
        public virtual ObjectResult<FacilitiesAndPhysicianByZipCodeDB> GetFacilitiesAndPhysicianByZipCode(string latitude, string longitude, string zipCode, string miles, string type)
        {
            var latitudeParameter = latitude != null ?
                new ObjectParameter("Latitude", latitude) :
                new ObjectParameter("Latitude", typeof(string));
    
            var longitudeParameter = longitude != null ?
                new ObjectParameter("Longitude", longitude) :
                new ObjectParameter("Longitude", typeof(string));
    
            var zipCodeParameter = zipCode != null ?
                new ObjectParameter("ZipCode", zipCode) :
                new ObjectParameter("ZipCode", typeof(string));
    
            var milesParameter = miles != null ?
                new ObjectParameter("Miles", miles) :
                new ObjectParameter("Miles", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FacilitiesAndPhysicianByZipCodeDB>("GetFacilitiesAndPhysicianByZipCode", latitudeParameter, longitudeParameter, zipCodeParameter, milesParameter, typeParameter);
        }
    }
}
