//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACR.Library.Ideas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRACTICE
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public string STREET { get; set; }
        public string STREET2 { get; set; }
        public string CITY { get; set; }
        public string STATE_ID { get; set; }
        public string ZIP { get; set; }
        public string PHONE { get; set; }
        public string FAX { get; set; }
        public string EMAIL { get; set; }
        public int STATUS { get; set; }
        public System.DateTime REGISTRATION_DATE { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DATE { get; set; }
        public Nullable<int> PRACTICE_TYPE { get; set; }
        public string PHONE_EXT { get; set; }
        public Nullable<int> LAST_UPDATE_USER_ID { get; set; }
        public Nullable<int> IRB_APPROVAL_TYPE { get; set; }
        public Nullable<bool> IS_PARTICIPATING_SITE_APPROVAL_EXECUTED { get; set; }
        public Nullable<bool> IS_IRB_APPROVED { get; set; }
        public Nullable<bool> IS_FACILITY_APPROVED { get; set; }
        public Nullable<bool> IS_DEMENTIA_SPECIALIST_APPROVED { get; set; }
        public System.DateTime CREATED_DATETIME { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> LAST_MODIFIED_DATETIME { get; set; }
        public string LAST_MODIFIED_BY { get; set; }
        public Nullable<bool> IS_ACTIVE { get; set; }
        public bool IS_DATA_COLLECTION_AVAILABLE { get; set; }
        public Nullable<System.DateTime> ORIGINAL_IRB_APPROVAL_DATE { get; set; }
        public Nullable<System.DateTime> IRB_EXPIRATION_DATE { get; set; }
        public Nullable<System.DateTime> SITE_ACTIVATION_DATE { get; set; }
        public Nullable<System.DateTime> SITE_WITHDRAWAL_DATE { get; set; }
        public bool IS_TERMINATED { get; set; }
        public string REASON_OF_TERMINATION { get; set; }
        public Nullable<decimal> LATITUDE { get; set; }
        public Nullable<decimal> LONGITUDE { get; set; }
    }
}
