//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACR.Foundation.CaseInPointService.CaseInPointService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CaseInPointService.Service1Soap")]
    public interface Service1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCaseData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetCaseData(string _3sToken, string publishDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCaseData", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetCaseDataAsync(string _3sToken, string publishDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPublishDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetPublishDate(string _3sToken, string CaseId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPublishDate", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetPublishDateAsync(string _3sToken, string CaseId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetToken", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetToken(string _3sUserName, string _3sPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetToken", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetTokenAsync(string _3sUserName, string _3sPassword);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : ACR.Foundation.CaseInPointService.CaseInPointService.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<ACR.Foundation.CaseInPointService.CaseInPointService.Service1Soap>, ACR.Foundation.CaseInPointService.CaseInPointService.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetCaseData(string _3sToken, string publishDate) {
            return base.Channel.GetCaseData(_3sToken, publishDate);
        }
        
        public System.Threading.Tasks.Task<string> GetCaseDataAsync(string _3sToken, string publishDate) {
            return base.Channel.GetCaseDataAsync(_3sToken, publishDate);
        }
        
        public string GetPublishDate(string _3sToken, string CaseId) {
            return base.Channel.GetPublishDate(_3sToken, CaseId);
        }
        
        public System.Threading.Tasks.Task<string> GetPublishDateAsync(string _3sToken, string CaseId) {
            return base.Channel.GetPublishDateAsync(_3sToken, CaseId);
        }
        
        public string GetToken(string _3sUserName, string _3sPassword) {
            return base.Channel.GetToken(_3sUserName, _3sPassword);
        }
        
        public System.Threading.Tasks.Task<string> GetTokenAsync(string _3sUserName, string _3sPassword) {
            return base.Channel.GetTokenAsync(_3sUserName, _3sPassword);
        }
    }
}
