//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACR.layouts.RLI {
    
    
    public partial class LtRLIHomepage {
        
        /// <summary>
        /// Analytics1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ACR.controls.RLI.Analytics Analytics1;
        
        /// <summary>
        /// rliHeaderBanner control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ACR.controls.RLI.HeaderBanner rliHeaderBanner;
        
        /// <summary>
        /// rliHeader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ACR.controls.RLI.Header rliHeader;
        
        /// <summary>
        /// rliCarousel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ACR.controls.RLI.Carousel rliCarousel;
    }
}
