variables:
- name: config_profile
  value: 'Prod-CD1'
- name: gl_taskname
  value: 'Deploy-Prod-CD'
- name: ch_path
  value: 'ProdCD'
- name: webroot
  value: './Output/ProdCD'

trigger:
- master

resources:
  repositories:
  - repository: SitecorePROD # The name used to reference this repository in the checkout step
    type: github
    endpoint: ACRCode
    name: ACRCode/Sitecore92_Production
    ref: master
    
pool:
  vmImage: 'windows-2019'
  #name: 'Local Agents' #vs2017-win2016
  #demands:
  #- agent.os -equals Windows_NT  # check for os string in capability

steps:
- checkout: SitecorePROD
  clean: true
  path: ${{ variables.ch_path }}

- task: NuGetCommand@2
  inputs:
    #command: 'restore'
    restoreSolution: 'src/ACRHelix/ACRHelix.sln'
    packagesDirectory: 'src/ACRHelix/packages'
    #feedsToUse: 'config'
    #nugetConfigPath: 'src/ACRHelix/nuget.config'

- task: VSBuild@1
  inputs:
    solution: 'src/ACRHelix/ACRHelix.sln'
    #vsVersion: '15.0'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true'
    configuration: ${{ variables.config_profile }}

- task: NodeTool@0 
  inputs:
    versionSpec: '12.13.0' # '14.18.1' #'12.13.0' # installs the version that the projects need

- task: Npm@1
  displayName: 'Cache Verify'
  inputs:
    command: custom
    verbose: false
    customCommand: 'cache verify'

- task: Npm@1
  displayName: 'Rebuild node-sass'
  inputs:
    command: 'custom'
    customCommand: 'rebuild node-sass --force'

- task: Npm@1
  displayName: 'NPM install'
  inputs:
    command: install # install dependency packages with package.json
    workingDir: 'src/ACRHelix'

- task: gulp@0
  inputs :
    gulpFile: 'src/ACRHelix/gulpfile.js'
    targets: ${{ variables.gl_taskname }}
    gulpjs: 'src/ACRHelix/node_modules/gulp/bin/gulp.js'
    enableCodeCoverage: false

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: ${{ variables.webroot }}
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: './Archives/CD-BuildOutput-$(Build.BuildId).zip' 
    replaceExistingArchive: true

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: ${{ variables.webroot }} 
    artifactName: 'dp'
    artifactType: 'pipeline' 