#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACR.Library.ImageWisely.Data
{
    using System.Data.Linq;
    using System.Data.Linq.Mapping;
    using System.Data;
    using System.Collections.Generic;
    using System.Reflection;
    using System.Linq;
    using System.Linq.Expressions;
    using System.ComponentModel;
    using System;
    using System.Configuration;

    [global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ACRTest1_WebsiteFormSubmissions")]
	public partial class PledgeSubmissionsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAssociationPledgeSubmission(AssociationPledgeSubmission instance);
    partial void UpdateAssociationPledgeSubmission(AssociationPledgeSubmission instance);
    partial void DeleteAssociationPledgeSubmission(AssociationPledgeSubmission instance);
    partial void InsertReferringPractitionerPledgeSubmission(ReferringPractitionerPledgeSubmission instance);
    partial void UpdateReferringPractitionerPledgeSubmission(ReferringPractitionerPledgeSubmission instance);
    partial void DeleteReferringPractitionerPledgeSubmission(ReferringPractitionerPledgeSubmission instance);
    partial void InsertPledgeSubmission(PledgeSubmission instance);
    partial void UpdatePledgeSubmission(PledgeSubmission instance);
    partial void DeletePledgeSubmission(PledgeSubmission instance);
    partial void InsertFacilityPledgeSubmission(FacilityPledgeSubmission instance);
    partial void UpdateFacilityPledgeSubmission(FacilityPledgeSubmission instance);
    partial void DeleteFacilityPledgeSubmission(FacilityPledgeSubmission instance);
    #endregion
		
        public PledgeSubmissionsDataContext() :
            base(ConfigurationManager.ConnectionStrings["ACR.Library.Properties.Settings.ACR_WebsiteFormSubmissionsConnectionString"].ConnectionString, mappingSource)
        {
            OnCreated();
        }

        public PledgeSubmissionsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PledgeSubmissionsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PledgeSubmissionsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PledgeSubmissionsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<AssociationPledgeSubmission> AssociationPledgeSubmissions
		{
			get
			{
				return this.GetTable<AssociationPledgeSubmission>();
			}
		}
		
		public System.Data.Linq.Table<ReferringPractitionerPledgeSubmission> ReferringPractitionerPledgeSubmissions
		{
			get
			{
				return this.GetTable<ReferringPractitionerPledgeSubmission>();
			}
		}
		
		public System.Data.Linq.Table<PledgeSubmission> PledgeSubmissions
		{
			get
			{
				return this.GetTable<PledgeSubmission>();
			}
		}
		
		public System.Data.Linq.Table<FacilityPledgeSubmission> FacilityPledgeSubmissions
		{
			get
			{
				return this.GetTable<FacilityPledgeSubmission>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AssociationPledgeSubmissions")]
	public partial class AssociationPledgeSubmission : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _First_Name;
		
		private string _Last_Name;
		
		private string _Email;
		
		private string _Title;
		
		private string _Association;
		
		private string _City;
		
		private string _State;
		
		private string _Country;
		
		private string _SubmissionEmailedTo;
		
		private System.DateTime _TimeSubmitted;
		
		private string _Status;
		
		private byte _DisplayOnHonorRoll;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnFirst_NameChanging(string value);
    partial void OnFirst_NameChanged();
    partial void OnLast_NameChanging(string value);
    partial void OnLast_NameChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnAssociationChanging(string value);
    partial void OnAssociationChanged();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnStateChanging(string value);
    partial void OnStateChanged();
    partial void OnCountryChanging(string value);
    partial void OnCountryChanged();
    partial void OnSubmissionEmailedToChanging(string value);
    partial void OnSubmissionEmailedToChanged();
    partial void OnTimeSubmittedChanging(System.DateTime value);
    partial void OnTimeSubmittedChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnDisplayOnHonorRollChanging(byte value);
    partial void OnDisplayOnHonorRollChanged();
    #endregion
		
		public AssociationPledgeSubmission()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[First Name]", Storage="_First_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string First_Name
		{
			get
			{
				return this._First_Name;
			}
			set
			{
				if ((this._First_Name != value))
				{
					this.OnFirst_NameChanging(value);
					this.SendPropertyChanging();
					this._First_Name = value;
					this.SendPropertyChanged("First_Name");
					this.OnFirst_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Last Name]", Storage="_Last_Name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Last_Name
		{
			get
			{
				return this._Last_Name;
			}
			set
			{
				if ((this._Last_Name != value))
				{
					this.OnLast_NameChanging(value);
					this.SendPropertyChanging();
					this._Last_Name = value;
					this.SendPropertyChanged("Last_Name");
					this.OnLast_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="VarChar(200)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Association", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string Association
		{
			get
			{
				return this._Association;
			}
			set
			{
				if ((this._Association != value))
				{
					this.OnAssociationChanging(value);
					this.SendPropertyChanging();
					this._Association = value;
					this.SendPropertyChanged("Association");
					this.OnAssociationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="VarChar(100)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this.OnCityChanging(value);
					this.SendPropertyChanging();
					this._City = value;
					this.SendPropertyChanged("City");
					this.OnCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="VarChar(100)")]
		public string State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this.OnStateChanging(value);
					this.SendPropertyChanging();
					this._State = value;
					this.SendPropertyChanged("State");
					this.OnStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country", DbType="VarChar(100)")]
		public string Country
		{
			get
			{
				return this._Country;
			}
			set
			{
				if ((this._Country != value))
				{
					this.OnCountryChanging(value);
					this.SendPropertyChanging();
					this._Country = value;
					this.SendPropertyChanged("Country");
					this.OnCountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubmissionEmailedTo", DbType="VarChar(255)")]
		public string SubmissionEmailedTo
		{
			get
			{
				return this._SubmissionEmailedTo;
			}
			set
			{
				if ((this._SubmissionEmailedTo != value))
				{
					this.OnSubmissionEmailedToChanging(value);
					this.SendPropertyChanging();
					this._SubmissionEmailedTo = value;
					this.SendPropertyChanged("SubmissionEmailedTo");
					this.OnSubmissionEmailedToChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeSubmitted", DbType="DateTime NOT NULL")]
		public System.DateTime TimeSubmitted
		{
			get
			{
				return this._TimeSubmitted;
			}
			set
			{
				if ((this._TimeSubmitted != value))
				{
					this.OnTimeSubmittedChanging(value);
					this.SendPropertyChanging();
					this._TimeSubmitted = value;
					this.SendPropertyChanged("TimeSubmitted");
					this.OnTimeSubmittedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(255)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisplayOnHonorRoll", DbType="TinyInt NOT NULL")]
		public byte DisplayOnHonorRoll
		{
			get
			{
				return this._DisplayOnHonorRoll;
			}
			set
			{
				if ((this._DisplayOnHonorRoll != value))
				{
					this.OnDisplayOnHonorRollChanging(value);
					this.SendPropertyChanging();
					this._DisplayOnHonorRoll = value;
					this.SendPropertyChanged("DisplayOnHonorRoll");
					this.OnDisplayOnHonorRollChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ReferringPractitionerPledgeSubmissions")]
	public partial class ReferringPractitionerPledgeSubmission : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _First_Name;
		
		private string _Last_Name;
		
		private string _Email;
		
		private string _Profession_Role;
		
		private string _Primary_Institution;
		
		private string _Country_of_Practice;
		
		private string _Primary_Practice_Type;
		
		private string _How_Learned_About_Image_Wisely;
		
		private byte _Contact_With_Updates;
		
		private byte _Participate_in_Follow_Up_Survey;
		
		private string _SubmissionEmailedTo;
		
		private System.DateTime _TimeSubmitted;
		
		private string _Status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnFirst_NameChanging(string value);
    partial void OnFirst_NameChanged();
    partial void OnLast_NameChanging(string value);
    partial void OnLast_NameChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnProfession_RoleChanging(string value);
    partial void OnProfession_RoleChanged();
    partial void OnPrimary_InstitutionChanging(string value);
    partial void OnPrimary_InstitutionChanged();
    partial void OnCountry_of_PracticeChanging(string value);
    partial void OnCountry_of_PracticeChanged();
    partial void OnPrimary_Practice_TypeChanging(string value);
    partial void OnPrimary_Practice_TypeChanged();
    partial void OnHow_Learned_About_Image_WiselyChanging(string value);
    partial void OnHow_Learned_About_Image_WiselyChanged();
    partial void OnContact_With_UpdatesChanging(byte value);
    partial void OnContact_With_UpdatesChanged();
    partial void OnParticipate_in_Follow_Up_SurveyChanging(byte value);
    partial void OnParticipate_in_Follow_Up_SurveyChanged();
    partial void OnSubmissionEmailedToChanging(string value);
    partial void OnSubmissionEmailedToChanged();
    partial void OnTimeSubmittedChanging(System.DateTime value);
    partial void OnTimeSubmittedChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    #endregion
		
		public ReferringPractitionerPledgeSubmission()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[First Name]", Storage="_First_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string First_Name
		{
			get
			{
				return this._First_Name;
			}
			set
			{
				if ((this._First_Name != value))
				{
					this.OnFirst_NameChanging(value);
					this.SendPropertyChanging();
					this._First_Name = value;
					this.SendPropertyChanged("First_Name");
					this.OnFirst_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Last Name]", Storage="_Last_Name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Last_Name
		{
			get
			{
				return this._Last_Name;
			}
			set
			{
				if ((this._Last_Name != value))
				{
					this.OnLast_NameChanging(value);
					this.SendPropertyChanging();
					this._Last_Name = value;
					this.SendPropertyChanged("Last_Name");
					this.OnLast_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Profession_Role", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string Profession_Role
		{
			get
			{
				return this._Profession_Role;
			}
			set
			{
				if ((this._Profession_Role != value))
				{
					this.OnProfession_RoleChanging(value);
					this.SendPropertyChanging();
					this._Profession_Role = value;
					this.SendPropertyChanged("Profession_Role");
					this.OnProfession_RoleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Primary Institution]", Storage="_Primary_Institution", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string Primary_Institution
		{
			get
			{
				return this._Primary_Institution;
			}
			set
			{
				if ((this._Primary_Institution != value))
				{
					this.OnPrimary_InstitutionChanging(value);
					this.SendPropertyChanging();
					this._Primary_Institution = value;
					this.SendPropertyChanged("Primary_Institution");
					this.OnPrimary_InstitutionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Country of Practice]", Storage="_Country_of_Practice", DbType="VarChar(100)")]
		public string Country_of_Practice
		{
			get
			{
				return this._Country_of_Practice;
			}
			set
			{
				if ((this._Country_of_Practice != value))
				{
					this.OnCountry_of_PracticeChanging(value);
					this.SendPropertyChanging();
					this._Country_of_Practice = value;
					this.SendPropertyChanged("Country_of_Practice");
					this.OnCountry_of_PracticeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Primary Practice Type]", Storage="_Primary_Practice_Type", DbType="VarChar(100)")]
		public string Primary_Practice_Type
		{
			get
			{
				return this._Primary_Practice_Type;
			}
			set
			{
				if ((this._Primary_Practice_Type != value))
				{
					this.OnPrimary_Practice_TypeChanging(value);
					this.SendPropertyChanging();
					this._Primary_Practice_Type = value;
					this.SendPropertyChanged("Primary_Practice_Type");
					this.OnPrimary_Practice_TypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[How Learned About Image Wisely]", Storage="_How_Learned_About_Image_Wisely", DbType="VarChar(255)")]
		public string How_Learned_About_Image_Wisely
		{
			get
			{
				return this._How_Learned_About_Image_Wisely;
			}
			set
			{
				if ((this._How_Learned_About_Image_Wisely != value))
				{
					this.OnHow_Learned_About_Image_WiselyChanging(value);
					this.SendPropertyChanging();
					this._How_Learned_About_Image_Wisely = value;
					this.SendPropertyChanged("How_Learned_About_Image_Wisely");
					this.OnHow_Learned_About_Image_WiselyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Contact With Updates]", Storage="_Contact_With_Updates", DbType="TinyInt NOT NULL")]
		public byte Contact_With_Updates
		{
			get
			{
				return this._Contact_With_Updates;
			}
			set
			{
				if ((this._Contact_With_Updates != value))
				{
					this.OnContact_With_UpdatesChanging(value);
					this.SendPropertyChanging();
					this._Contact_With_Updates = value;
					this.SendPropertyChanged("Contact_With_Updates");
					this.OnContact_With_UpdatesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Participate in Follow Up Survey]", Storage="_Participate_in_Follow_Up_Survey", DbType="TinyInt NOT NULL")]
		public byte Participate_in_Follow_Up_Survey
		{
			get
			{
				return this._Participate_in_Follow_Up_Survey;
			}
			set
			{
				if ((this._Participate_in_Follow_Up_Survey != value))
				{
					this.OnParticipate_in_Follow_Up_SurveyChanging(value);
					this.SendPropertyChanging();
					this._Participate_in_Follow_Up_Survey = value;
					this.SendPropertyChanged("Participate_in_Follow_Up_Survey");
					this.OnParticipate_in_Follow_Up_SurveyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubmissionEmailedTo", DbType="VarChar(255)")]
		public string SubmissionEmailedTo
		{
			get
			{
				return this._SubmissionEmailedTo;
			}
			set
			{
				if ((this._SubmissionEmailedTo != value))
				{
					this.OnSubmissionEmailedToChanging(value);
					this.SendPropertyChanging();
					this._SubmissionEmailedTo = value;
					this.SendPropertyChanged("SubmissionEmailedTo");
					this.OnSubmissionEmailedToChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeSubmitted", DbType="DateTime NOT NULL")]
		public System.DateTime TimeSubmitted
		{
			get
			{
				return this._TimeSubmitted;
			}
			set
			{
				if ((this._TimeSubmitted != value))
				{
					this.OnTimeSubmittedChanging(value);
					this.SendPropertyChanging();
					this._TimeSubmitted = value;
					this.SendPropertyChanged("TimeSubmitted");
					this.OnTimeSubmittedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(255)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PledgeSubmissions")]
	public partial class PledgeSubmission : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _First_Name;
		
		private string _Last_Name;
		
		private string _Email;
		
		private string _Profession_Role;
		
		private string _Primary_Institution;
		
		private string _Country_of_Practice;
		
		private string _Primary_Practice_Type;
		
		private string _How_Learned_About_Image_Wisely;
		
		private byte _Contact_With_Updates;
		
		private byte _Participate_in_Follow_Up_Survey;
		
		private string _SubmissionEmailedTo;
		
		private System.DateTime _TimeSubmitted;
		
		private string _Status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnFirst_NameChanging(string value);
    partial void OnFirst_NameChanged();
    partial void OnLast_NameChanging(string value);
    partial void OnLast_NameChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnProfession_RoleChanging(string value);
    partial void OnProfession_RoleChanged();
    partial void OnPrimary_InstitutionChanging(string value);
    partial void OnPrimary_InstitutionChanged();
    partial void OnCountry_of_PracticeChanging(string value);
    partial void OnCountry_of_PracticeChanged();
    partial void OnPrimary_Practice_TypeChanging(string value);
    partial void OnPrimary_Practice_TypeChanged();
    partial void OnHow_Learned_About_Image_WiselyChanging(string value);
    partial void OnHow_Learned_About_Image_WiselyChanged();
    partial void OnContact_With_UpdatesChanging(byte value);
    partial void OnContact_With_UpdatesChanged();
    partial void OnParticipate_in_Follow_Up_SurveyChanging(byte value);
    partial void OnParticipate_in_Follow_Up_SurveyChanged();
    partial void OnSubmissionEmailedToChanging(string value);
    partial void OnSubmissionEmailedToChanged();
    partial void OnTimeSubmittedChanging(System.DateTime value);
    partial void OnTimeSubmittedChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    #endregion
		
		public PledgeSubmission()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[First Name]", Storage="_First_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string First_Name
		{
			get
			{
				return this._First_Name;
			}
			set
			{
				if ((this._First_Name != value))
				{
					this.OnFirst_NameChanging(value);
					this.SendPropertyChanging();
					this._First_Name = value;
					this.SendPropertyChanged("First_Name");
					this.OnFirst_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Last Name]", Storage="_Last_Name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Last_Name
		{
			get
			{
				return this._Last_Name;
			}
			set
			{
				if ((this._Last_Name != value))
				{
					this.OnLast_NameChanging(value);
					this.SendPropertyChanging();
					this._Last_Name = value;
					this.SendPropertyChanged("Last_Name");
					this.OnLast_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Profession_Role", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string Profession_Role
		{
			get
			{
				return this._Profession_Role;
			}
			set
			{
				if ((this._Profession_Role != value))
				{
					this.OnProfession_RoleChanging(value);
					this.SendPropertyChanging();
					this._Profession_Role = value;
					this.SendPropertyChanged("Profession_Role");
					this.OnProfession_RoleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Primary Institution]", Storage="_Primary_Institution", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string Primary_Institution
		{
			get
			{
				return this._Primary_Institution;
			}
			set
			{
				if ((this._Primary_Institution != value))
				{
					this.OnPrimary_InstitutionChanging(value);
					this.SendPropertyChanging();
					this._Primary_Institution = value;
					this.SendPropertyChanged("Primary_Institution");
					this.OnPrimary_InstitutionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Country of Practice]", Storage="_Country_of_Practice", DbType="VarChar(100)")]
		public string Country_of_Practice
		{
			get
			{
				return this._Country_of_Practice;
			}
			set
			{
				if ((this._Country_of_Practice != value))
				{
					this.OnCountry_of_PracticeChanging(value);
					this.SendPropertyChanging();
					this._Country_of_Practice = value;
					this.SendPropertyChanged("Country_of_Practice");
					this.OnCountry_of_PracticeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Primary Practice Type]", Storage="_Primary_Practice_Type", DbType="VarChar(100)")]
		public string Primary_Practice_Type
		{
			get
			{
				return this._Primary_Practice_Type;
			}
			set
			{
				if ((this._Primary_Practice_Type != value))
				{
					this.OnPrimary_Practice_TypeChanging(value);
					this.SendPropertyChanging();
					this._Primary_Practice_Type = value;
					this.SendPropertyChanged("Primary_Practice_Type");
					this.OnPrimary_Practice_TypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[How Learned About Image Wisely]", Storage="_How_Learned_About_Image_Wisely", DbType="VarChar(255)")]
		public string How_Learned_About_Image_Wisely
		{
			get
			{
				return this._How_Learned_About_Image_Wisely;
			}
			set
			{
				if ((this._How_Learned_About_Image_Wisely != value))
				{
					this.OnHow_Learned_About_Image_WiselyChanging(value);
					this.SendPropertyChanging();
					this._How_Learned_About_Image_Wisely = value;
					this.SendPropertyChanged("How_Learned_About_Image_Wisely");
					this.OnHow_Learned_About_Image_WiselyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Contact With Updates]", Storage="_Contact_With_Updates", DbType="TinyInt NOT NULL")]
		public byte Contact_With_Updates
		{
			get
			{
				return this._Contact_With_Updates;
			}
			set
			{
				if ((this._Contact_With_Updates != value))
				{
					this.OnContact_With_UpdatesChanging(value);
					this.SendPropertyChanging();
					this._Contact_With_Updates = value;
					this.SendPropertyChanged("Contact_With_Updates");
					this.OnContact_With_UpdatesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Participate in Follow Up Survey]", Storage="_Participate_in_Follow_Up_Survey", DbType="TinyInt NOT NULL")]
		public byte Participate_in_Follow_Up_Survey
		{
			get
			{
				return this._Participate_in_Follow_Up_Survey;
			}
			set
			{
				if ((this._Participate_in_Follow_Up_Survey != value))
				{
					this.OnParticipate_in_Follow_Up_SurveyChanging(value);
					this.SendPropertyChanging();
					this._Participate_in_Follow_Up_Survey = value;
					this.SendPropertyChanged("Participate_in_Follow_Up_Survey");
					this.OnParticipate_in_Follow_Up_SurveyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubmissionEmailedTo", DbType="VarChar(255)")]
		public string SubmissionEmailedTo
		{
			get
			{
				return this._SubmissionEmailedTo;
			}
			set
			{
				if ((this._SubmissionEmailedTo != value))
				{
					this.OnSubmissionEmailedToChanging(value);
					this.SendPropertyChanging();
					this._SubmissionEmailedTo = value;
					this.SendPropertyChanged("SubmissionEmailedTo");
					this.OnSubmissionEmailedToChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeSubmitted", DbType="DateTime NOT NULL")]
		public System.DateTime TimeSubmitted
		{
			get
			{
				return this._TimeSubmitted;
			}
			set
			{
				if ((this._TimeSubmitted != value))
				{
					this.OnTimeSubmittedChanging(value);
					this.SendPropertyChanging();
					this._TimeSubmitted = value;
					this.SendPropertyChanged("TimeSubmitted");
					this.OnTimeSubmittedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(255)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FacilityPledgeSubmissions")]
	public partial class FacilityPledgeSubmission : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _First_Name;
		
		private string _Last_Name;
		
		private string _Email;
		
		private string _Title;
		
		private string _Facility;
		
		private string _City;
		
		private string _State;
		
		private string _Country;
		
		private string _SubmissionEmailedTo;
		
		private System.DateTime _TimeSubmitted;
		
		private string _Status;
		
		private byte _DisplayOnHonorRoll;
		
		private System.Nullable<byte> _Level1;
		
		private System.Nullable<byte> _Level2;
		
		private System.Nullable<byte> _Level3;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnFirst_NameChanging(string value);
    partial void OnFirst_NameChanged();
    partial void OnLast_NameChanging(string value);
    partial void OnLast_NameChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnFacilityChanging(string value);
    partial void OnFacilityChanged();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnStateChanging(string value);
    partial void OnStateChanged();
    partial void OnCountryChanging(string value);
    partial void OnCountryChanged();
    partial void OnSubmissionEmailedToChanging(string value);
    partial void OnSubmissionEmailedToChanged();
    partial void OnTimeSubmittedChanging(System.DateTime value);
    partial void OnTimeSubmittedChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnDisplayOnHonorRollChanging(byte value);
    partial void OnDisplayOnHonorRollChanged();
    partial void OnLevel1Changing(System.Nullable<byte> value);
    partial void OnLevel1Changed();
    partial void OnLevel2Changing(System.Nullable<byte> value);
    partial void OnLevel2Changed();
    partial void OnLevel3Changing(System.Nullable<byte> value);
    partial void OnLevel3Changed();
    #endregion
		
		public FacilityPledgeSubmission()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[First Name]", Storage="_First_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string First_Name
		{
			get
			{
				return this._First_Name;
			}
			set
			{
				if ((this._First_Name != value))
				{
					this.OnFirst_NameChanging(value);
					this.SendPropertyChanging();
					this._First_Name = value;
					this.SendPropertyChanged("First_Name");
					this.OnFirst_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Last Name]", Storage="_Last_Name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Last_Name
		{
			get
			{
				return this._Last_Name;
			}
			set
			{
				if ((this._Last_Name != value))
				{
					this.OnLast_NameChanging(value);
					this.SendPropertyChanging();
					this._Last_Name = value;
					this.SendPropertyChanged("Last_Name");
					this.OnLast_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="VarChar(200)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Facility", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string Facility
		{
			get
			{
				return this._Facility;
			}
			set
			{
				if ((this._Facility != value))
				{
					this.OnFacilityChanging(value);
					this.SendPropertyChanging();
					this._Facility = value;
					this.SendPropertyChanged("Facility");
					this.OnFacilityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="VarChar(100)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this.OnCityChanging(value);
					this.SendPropertyChanging();
					this._City = value;
					this.SendPropertyChanged("City");
					this.OnCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="VarChar(100)")]
		public string State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this.OnStateChanging(value);
					this.SendPropertyChanging();
					this._State = value;
					this.SendPropertyChanged("State");
					this.OnStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country", DbType="VarChar(100)")]
		public string Country
		{
			get
			{
				return this._Country;
			}
			set
			{
				if ((this._Country != value))
				{
					this.OnCountryChanging(value);
					this.SendPropertyChanging();
					this._Country = value;
					this.SendPropertyChanged("Country");
					this.OnCountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubmissionEmailedTo", DbType="VarChar(255)")]
		public string SubmissionEmailedTo
		{
			get
			{
				return this._SubmissionEmailedTo;
			}
			set
			{
				if ((this._SubmissionEmailedTo != value))
				{
					this.OnSubmissionEmailedToChanging(value);
					this.SendPropertyChanging();
					this._SubmissionEmailedTo = value;
					this.SendPropertyChanged("SubmissionEmailedTo");
					this.OnSubmissionEmailedToChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeSubmitted", DbType="DateTime NOT NULL")]
		public System.DateTime TimeSubmitted
		{
			get
			{
				return this._TimeSubmitted;
			}
			set
			{
				if ((this._TimeSubmitted != value))
				{
					this.OnTimeSubmittedChanging(value);
					this.SendPropertyChanging();
					this._TimeSubmitted = value;
					this.SendPropertyChanged("TimeSubmitted");
					this.OnTimeSubmittedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(255)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisplayOnHonorRoll", DbType="TinyInt NOT NULL")]
		public byte DisplayOnHonorRoll
		{
			get
			{
				return this._DisplayOnHonorRoll;
			}
			set
			{
				if ((this._DisplayOnHonorRoll != value))
				{
					this.OnDisplayOnHonorRollChanging(value);
					this.SendPropertyChanging();
					this._DisplayOnHonorRoll = value;
					this.SendPropertyChanged("DisplayOnHonorRoll");
					this.OnDisplayOnHonorRollChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Level1", DbType="TinyInt")]
		public System.Nullable<byte> Level1
		{
			get
			{
				return this._Level1;
			}
			set
			{
				if ((this._Level1 != value))
				{
					this.OnLevel1Changing(value);
					this.SendPropertyChanging();
					this._Level1 = value;
					this.SendPropertyChanged("Level1");
					this.OnLevel1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Level2", DbType="TinyInt")]
		public System.Nullable<byte> Level2
		{
			get
			{
				return this._Level2;
			}
			set
			{
				if ((this._Level2 != value))
				{
					this.OnLevel2Changing(value);
					this.SendPropertyChanging();
					this._Level2 = value;
					this.SendPropertyChanged("Level2");
					this.OnLevel2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Level3", DbType="TinyInt")]
		public System.Nullable<byte> Level3
		{
			get
			{
				return this._Level3;
			}
			set
			{
				if ((this._Level3 != value))
				{
					this.OnLevel3Changing(value);
					this.SendPropertyChanging();
					this._Level3 = value;
					this.SendPropertyChanged("Level3");
					this.OnLevel3Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
